baseURL = "https://www.bradlecon.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "David Bradley"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "David Bradley"
author = "David Bradley"
description = ""
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/david-bradley-9a9059b0"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/davidby332"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "davidby332@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Resume"
  weight = 200
  identifier = "resume"
  url = "/files/resume_11_20.pdf"

  [[menu.main]]
  name = "Projects"
  weight = 300
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "Research"
  weight = 400
  identifier = "research"
  url = "/research/"
